name 'gehel-cntlm'
version '1.0.0'

author 'Guillaume Lederrey'
license 'Apache2'
project_page 'https://github.com/gehel/puppet-cntlm'
source 'https://github.com/gehel/puppet-cntlm'
summary 'Puppet module for cntlm'
description 'This module installs and manages cntlm. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
